#!/usr/bin/env python
__author__ = 'nafisa'
import rospy
import json
import sys
import time
import math
from std_msgs.msg import String, Bool, Float32MultiArray

class DeconController:
	def __init__(self):
		
		self.led_command_topic = rospy.Publisher('led_msg', Bool, queue_size=1)
		self.pump_command_topic = rospy.Publisher('pump_msg', Bool, queue_size=1)
		self.detection_command_topic = rospy.Publisher('detect_msg', Bool, queue_size=1)
		self.detection_status_topic = rospy.Subscriber('detect_status_msg', Float32MultiArray, self.detection_cb)
		rospy.init_node('decon_controller', anonymous=True, disable_signals=True)

		self.handshake = False		
		self.rate = rospy.Rate(1) #Repeat detect and disinfect every 1 second
		self.detection_response = None
		self.detection_timeout = 30 #time in seconds (equal to 30 seconds)

	def detect(self):
		rospy.loginfo("[Decon] Starting detection process...")
		self.detection_command_topic.publish(True)
	
	def detection_cb(self, data):
		self.detection_response = data.data
		if self.detection_response == (1,) and self.handshake == False:
			self.handshake = True
			self.detection_response = None
			rospy.loginfo("[Decon] Detection handshake completed...")

	def turn_led_on(self):
		rospy.loginfo("[Decon] Turning led on...")
		self.led_command_topic.publish(True)

	def turn_led_off(self):
		rospy.loginfo("[Decon] Turning led off...")
		self.led_command_topic.publish(False)

	def activating_pump(self):
		rospy.loginfo("[Decon] Activating pump (It will turn off on its own after 30 seconds)...")
		self.pump_command_topic.publish(True)
	
	def disinfect(self):
		self.turn_led_on()
		for remaining in range(5, 0, -1):
    			sys.stdout.write("\r")
    			sys.stdout.write("{:2d} seconds remaining.".format(remaining)) 
    			sys.stdout.flush()
    			time.sleep(1)

		sys.stdout.write("\rComplete!            \n")
		self.turn_led_off()
		self.activating_pump()
		for remaining in range(5, 0, -1):
    			sys.stdout.write("\r")
    			sys.stdout.write("{:2d} seconds remaining.".format(remaining)) 
    			sys.stdout.flush()
    			time.sleep(1)


	def handshake_detection(self):
		rospy.loginfo("[Decon] Initiating handshake...")
		self.detection_command_topic.publish(False)

	def start(self):
		rospy.loginfo("[Decon] System Activated...")
		while not rospy.is_shutdown():
			timeout_start = time.time()
			try:
				while self.handshake is False and time.time() < timeout_start + 60:
					self.handshake_detection()
					self.rate.sleep()	
			except KeyboardInterrupt:
				rospy.loginfo("\n[Decon] Keyboard Interrupt received... GoodBye!")
				break
			if self.handshake is False:
				rospy.loginfo("[Decon] Detection not working... Try again later!")
				break
			self.detect()

			try:
				timer = -1
				while self.detection_response is None:
					timer += 1
					sys.stdout.write("\r")
					sys.stdout.write("{:3d} seconds elapsed.".format(int(timer)))
					sys.stdout.flush()
					self.rate.sleep()
			except KeyboardInterrupt:
				rospy.loginfo("\n[Decon] Keyboard Interrupt received...Releasing detection unit!")
			sys.stdout.write("\n")

			if self.detection_response is not None:
				if self.detection_response == (-1,):
                                	rospy.loginfo("\r[Decon] Camera could not capture. Try replugging camera cable...")
                                	self.handshake = False
				
				if len(self.detection_response) > 1:
					rospy.loginfo("[Decon] %s, I heard %s" % (rospy.get_caller_id(), ', '.join([str(elem) for elem in self.detection_response])))	
					[w,h,d,s,k] = self.detection_response[:5]
					objects = []
					for idx in range(0, len(self.detection_response[5:]), 5):
						#if self.detection_response[5+idx] == 1: #If the object is human
						#	stopAllMovement/Emergency Kill Switch Operation 
						if self.detection_response[5+idx] > 1: #If the object is door handle or light switch
							obj_width_in_meters = self.detection_response[8+idx]*s
							obj_height_in_meters = self.detection_response[9+idx]*k
							obj_horizontal_offset_from_arm_ee = ((w/2) - self.detection_response[6+idx]) * s
							obj_vertical_offset_from_arm_ee =  self.detection_response[7+idx]*k - d*math.tan(math.radians(30)) - 0.36 #Arm End Effector From Camera distance in sleep position is 0.36 m
							
							if obj_width_in_meters < 0.2 and obj_height_in_meters < 0.2: #Cross section of disinfecting cone is 0.25X0.25, hence the number 0.2
								#move_robot_ahead(d-0.45)
								#move_arm(obj_horizontal_offset_from_arm_ee, obj_vertical_offset_from_arm_ee)
								self.disinfect()
								#move_arm_home_pose()
								
				self.detection_response = None
			else:
				self.handshake = False

			self.rate.sleep()		
				
if __name__ == '__main__':
	try:
		dcontroller = DeconController()
		dcontroller.start()
	except rospy.ROSInterruptException:
		log_string = "[Decon] Decon Controller exiting at %s!" % rospy.get_time()	
		rospy.loginfo(log_string)

